### ISSUE TITLE
Increasing Memory Consumption

### ISSUE THREAD

**Issue by steffenbeermann** [Azure/Industrial-IoT#2365]
**Describe the bug**
We noticed that we are running out of memory sometimes on the devices running IoT Edge with the OPC Publisher. After investigating, we noticed that the OPC Publisher module takes more and more memory over time, see:
![Image](https://github.com/user-attachments/assets/e86eed45-141d-4fc9-a0ee-edb6dcd8047f)

Restarting the module will reset the memory usage (see dip at start of the graph). 
We noticed the same behavior on OPC Publisher 2.9.11 and 2.9.0

**To Reproduce**
We have the following config:
```
{
  "Hostname": "publisher_axh_active",
  "Cmd": [
    "--cl=5",
    "--cf",
    "--aa",
    "--pf=/mount/publishednodes.json",
    "--PkiRootPath=/mount/pki",
    "--si=90",
    "--di=3600"
  ],
  "HostConfig": {
    "Binds": [
      "/home/edge/OPCPublisherMount_Active:/mount"
    ]
  }
}
```

and we have around 20 endpoints configured with a total of around 200.000 Nodes in multiple subscription.

On an older version 2.8.1 it seems to run fine without increasing memory over time:
![Image](https://github.com/user-attachments/assets/c680a99a-1a81-40a1-8c5d-9ac20198a20e)

**Expected behavior**
The OPC Publisher does its garbage collection it self and does not built up high memory usages

**Comment by marcschier** [comment]
Could you run without Prometheus by setting `--em=False`?  

Also, how does the oom show for you?

**Comment by steffenbeermann** [comment]
We rely on the metrics of the OPC publisher module. With disabling Prometheus, the edge metric collector will still function right?

We noticed the issue because the IoT Edge runtime crashed and restarted all modules. It failed for a few hours until it went up again. See the drop of the memory on the 10th of November:
![Image](https://github.com/user-attachments/assets/bb8c04b5-ce08-487b-99cd-901cd346f3ca)

This goes along with a downtime of all modules for about 3 hours, where they did not respond. After some automatic restarts all modules went up again on their own.

**Comment by marcschier** [comment]
Could you take a look at the diagnostic log and check the numbers of the data flow pipeline (encoder related, send queue, egress, etc.), check if they are low or increasing?  That could mean we need to tune the data flow path to not hold on to incoming data it cannot send out.

My colleague also found a resource leak in the security handshake of the OPC UA stack.  But it is likely not enough to explain the increases.  Especially the huge increase at the end of the run from 2->4GB.

**Comment by steffenbeermann** [comment]
I have this diagnostic info for one endpoint:
```
    "sentMessagesPerSec": 0.12591434486187222,
    "ingestionDuration": "6.17:47:16.9692019",
    "ingressDataChanges": 3494295,
    "ingressValueChanges": 12381772,
    "ingressBatchBlockBufferSize": 48,
    "encodingBlockInputSize": 0,
    "encodingBlockOutputSize": 0,
    "encoderNotificationsProcessed": 3495567,
    "encoderNotificationsDropped": 0,
    "encoderIoTMessagesProcessed": 73343,
    "encoderAvgNotificationsMessage": 47.660540201519055,
    "encoderAvgIoTMessageBodySize": 37767.330201928016,
    "encoderAvgIoTChunkUsage": 9.220539600080082,
    "estimatedIoTChunksPerDay": 0,
    "outgressInputBufferCount": 0,
    "outgressInputBufferDropped": 0,
    "outgressIoTMessageCount": 73336,
    "connectionRetries": 0,
    "opcEndpointConnected": true,
    "monitoredOpcNodesSucceededCount": 6862,
    "monitoredOpcNodesFailedCount": 0,
    "ingressEventNotifications": 0,
    "ingressEvents": 0,
    "encoderMaxMessageSplitRatio": 0,
    "ingressDataChangesInLastMinute": 360,
    "ingressValueChangesInLastMinute": 1144,
    "ingressHeartbeats": 0,
    "ingressCyclicReads": 0
```

I don't exactly understand what you mean with data flow pipeline?

**Comment by steffenbeermann** [comment]
> Could you run without Prometheus by setting `--em=False`?
> 
> Also, how does the oom show for you?

I tried with the setting `--em=False` but it seems it did not solved the problem as there is still an slow increase over the last two weeks:
![Image](https://github.com/user-attachments/assets/040fefa2-9e59-48cd-af63-3840ede1d543)

**Comment by dimtix** [comment]
Hi everyone,

we’re seeing the same runaway–memory / auto-restart pattern **after upgrading from Publisher 2.9.11 to 2.9.12 and now 2.9.14**:

 **2.9.11** - Memory stays flat; no restarts. 
 **2.9.12 - 2.9.14** - Memory climbs steadily until the container limit is hit; the publisher container is then restarted.|

In our tests the climb is much more quicker as here described, most likely because the overall workload is higher. 
You can clearly see each restart in the attached screenshots: memory jumps back to its baseline and the cycle starts again:
**2.9.12**

![Image](https://github.com/user-attachments/assets/5f8baef9-61e0-43ac-944d-879dba3e438c)

**2.9.14**

![Image](https://github.com/user-attachments/assets/cc83983f-cda9-4508-b0de-698eadbb47ff)

Earlier in this thread was mentioned reproducing the issue on **2.9.11** as well, but we haven’t been able to—everything is stable for us on that version.

Let me know if logs or additional metrics would help. I can provide them right away.

Thanks!

**Comment by dimtix** [comment]
I reproduced the issue locally using Visual Studio with a setup that mirrors our production environment.  
The Publisher was launched from the latest **main** branch with the Visual Studio memory profiler with the following start parameters:

`
"commandLineArgs": "--messagingmode=FullNetworkMessages --BatchSize=10 --LingerTimeoutSeconds=60 --DisableDataSetMetaData=false --ApplicationUri=urn:opc-publisher:machine --BatchTriggerInterval=1000 --UseStandardsCompliantEncoding=True --RootTopicTemplate=opc-publisher --SiteId=machine --DefaultMetaDataUpdateTime=0 --CreatePublishFileIfNotExist=true --DefaultMessageTimeToLive=648000000 --LogLevel=Information --DefaultQueueSize=100 --DisableSessionPerWriterGroup=true --MaxPublishRequests=20 --MqttClientId=publisher --DefaultTransport=Mqtt --DefaultSamplingInterval=50 --PublisherId=machine --TelemetryTopicTemplate={RootTopic}/default/messages/{DataSetWriterGroup} --PublishedNodesFile=c:/temp/pn.json --DiagnosticsTopicTemplate={RootTopic}/default/diagnostics/{DataSetWriterGroup} --EnableRoutingInfo=True --MqttClientConnectionString=HostName=localhost;Port=1883;Protocol='v5' --UnsecureHttpServerPort=8080 --EventsTopicTemplate={RootTopic}/default/events/{DataSetWriterGroup}"
`

Memory snapshots after 5 min and  after 10 min already show a noticeable increase:

![Image](https://github.com/user-attachments/assets/9cb81360-eda7-4eb0-b3a6-1b368a94c618)

Corresponding Visual Studio `diagsession` file with memory snapshots (ZIP archive split into 6 parts—please remove the “.zip” extension from each downloaded part before extracting -  had to do this because of GitHub’s upload restrictions):

[Report20250526-1558.zip.001.zip](https://github.com/user-attachments/files/20442615/Report20250526-1558.zip.001.zip)
[Report20250526-1558.zip.002.zip](https://github.com/user-attachments/files/20442624/Report20250526-1558.zip.002.zip)
[Report20250526-1558.zip.003.zip](https://github.com/user-attachments/files/20442628/Report20250526-1558.zip.003.zip)
[Report20250526-1558.zip.004.zip](https://github.com/user-attachments/files/20442631/Report20250526-1558.zip.004.zip)
[Report20250526-1558.zip.005.zip](https://github.com/user-attachments/files/20442633/Report20250526-1558.zip.005.zip)
[Report20250526-1558.zip.006.zip](https://github.com/user-attachments/files/20442635/Report20250526-1558.zip.006.zip)

Please let me know if any additional details or alternative test setups would help.

**Comment by quality-leftovers** [comment]
On first look: Might be missing Unregister, linking the ApplicationMessages to NetworkMessageSink CancellationTokenSource?

https://github.com/microsoft/project-furly/blob/14bb95d235f2e68d43d312face99bec9b98aed35/src/Furly.Extensions.Mqtt/src/Clients/MqttSession.cs#L231

Probably affecting all deployments using MQTT after porting to MQTT NET 5?

(if so maybe a seperate issue makes sense to better differentiate from the original one)

**Comment by marcschier** [comment]
Thanks for the detailed analysis.  I am currently looking at other issues, but will prioritize this highest for next release.

**Comment by marcschier** [comment]
In 2.9.15 I am testing @dimtix command line but with -t Null and see no memory increases.  I have fixed to dispose all cancellation token sources in mqtt, so if it is mqtt, we should also look better.  However, initial report was with IoT Hub, which I will also test next.

**Comment by marcschier** [comment]
I have tested with IoT Edge and see no unexpected increases either (around 1 hour).  Other than a lost CancellationTokenSource in metadataloader which I have a fix for.

**Comment by Haeavar** [comment]
Hi @marcschier 
We still see increasing memory with the 2.9.15 preview 3 version (2.9.15-rc.11+ab2ed629df (.NET 9.0.7/linux-x64/OPC Stack 1.5.376.235)). Please let me know if I can provide more information regarding thi issue.

<img width="1466" height="237" alt="Image" src="https://github.com/user-attachments/assets/44bd780a-dca0-4181-aea1-97375491ea77" />

These are the env parameters we are using for the OpcPublisher
      "environment": [
        {
          "name": "DOTNET_gcServer",
          "value": "0"
        },
        {
          "name": "LogLevel",
          "value": "{{ .Values.app.opcPublisherLogLevel }}"
        },
        {
          "name": "Logging__LogLevel__Microsoft.AspNetCore",
          "value": "Warning"
        },
        {
          "name": "Logging__LogLevel__Azure.IIoT.OpcUa.Publisher.Stack.Services",
          "value": "Warning"
        },
        {
          "name": "PublishedNodesFile",
          "value": "/appdata/pn.json"
        },
        {
          "name": "CreatePublishFileIfNotExist",
          "value": "true"
        },
        {
          "name": "DefaultTransport",
          "value": "Mqtt"
        },
        {
          "name": "MqttClientConnectionString",
          "value": "HostName=localhost;Port=1883;Protocol='v5'"
        },
        {
          "name": "MqttClientId",
          "value": "publisher"
        },
        {
          "name": "EnableRoutingInfo",
          "value": "true"
        },
        {
          "name": "RootTopicTemplate",
          "value": "opc-publisher"
        },
        {
          "name": "TelemetryTopicTemplate",
          "value": "{RootTopic}/default/messages/{DataSetWriterGroup}"
        },
        {
          "name": "EventsTopicTemplate",
          "value": "{RootTopic}/default/events/{DataSetWriterGroup}"
        },
        {
          "name": "DiagnosticsTopicTemplate",
          "value": "{RootTopic}/default/diagnostics/{DataSetWriterGroup}"
        },
        {
          "name": "MessagingMode",
          "value": "FullNetworkMessages"
        },
        {
          "name": "MessageEncoding",
          "value": "Json"
        },
        {
          "name": "UseStandardsCompliantEncoding",
          "value": "True"
        },
        {
          "name": "DefaultQueueSize",
          "value": "10000"
        },
        {
          "name": "DefaultSamplingInterval",
          "value": "0"
        },
        {
          "name": "PublisherId",
          "value": "{{ .Values.sponsorRef }}"
        },
        {
          "name": "SiteId",
          "value": "{{ .Values.sponsorId }}"
        },
        {
          "name": "BatchTriggerInterval",
          "value": "00:00:02"
        },
        {
          "name": "BatchSize",
          "value": "50"
        },
        {
          "name": "DisableDataSetMetaData",
          "value": "false"
        },
        {
          "name": "DefaultMetaDataUpdateTime",
          "value": "0"
        },
        {
          "name": "ApplicationUri",
          "value": "urn:opc-publisher:sfh:{{ .Values.sponsorRef }}"
        },
        {
          "name": "UnsecureHttpServerPort",
          "value": "8083"
        },
        {
          "name": "HttpServerPort",
          "value": "8443"
        },
        {
          "name": "ApiKey",
          "value": "*****"
        },
        {
          "name": "DisableOpenApiEndpoint",
          "value": "true"
        },
        {
          "name": "DefaultMessageTimeToLive",
          "value": "180:00:00"
        },
        {
          "name": "MaxPublishRequests",
          "value": "20"
        },
        {
          "name": "DisableSessionPerWriterGroup",
          "value": "true"
        }
      ]


And these are the `/v2/diagnostics/connections` information:

[
  {
    "connection": {
      "endpoint": {
        "url": "opc.tcp://localhost:21878",
        "securityMode": "none"
      }
    },
    "server": {
      "sessionId": "nsu=urn:Z0008A0011:UnifiedAutomation:UaGateway;g=d1b602c7-4e90-4a57-bec5-7bddc79d3f0f",
      "sessionName": "opc.tcp://localhost:21878_7983A76F",
      "serverUri": "urn:Z0008A0011:UnifiedAutomation:UaGateway",
      "actualSessionTimeout": 60000,
      "maxResponseMessageSize": 8388608,
      "connectTime": "2025-08-11T06:58:01.2524722Z",
      "lastContactTime": "2025-08-11T07:00:41.3419463Z",
      "currentSubscriptionsCount": 1,
      "currentMonitoredItemsCount": 25,
      "currentPublishRequestsInQueue": 2,
      "totalRequestCount": {
        "totalCount": 814
      },
      "readCount": {
        "totalCount": 514
      },
      "callCount": {
        "totalCount": 1
      },
      "createMonitoredItemsCount": {
        "totalCount": 2
      },
      "createSubscriptionCount": {
        "totalCount": 1
      },
      "setPublishingModeCount": {
        "totalCount": 1
      },
      "publishCount": {
        "totalCount": 28
      },
      "browseCount": {
        "totalCount": 266
      },
      "translateBrowsePathsToNodeIdsCount": {
        "totalCount": 1
      },
      "subscriptions": [
        {
          "subscriptionId": 2183356782,
          "priority": 255,
          "publishingInterval": 1000,
          "maxKeepAliveCount": 10,
          "maxLifetimeCount": 30,
          "currentKeepAliveCount": 5,
          "maxNotificationsPerPublish": 65536,
          "publishingEnabled": true,
          "enableCount": 1,
          "monitoredItemCount": 25,
          "publishRequestCount": 26,
          "dataChangeNotificationsCount": 45,
          "eventNotificationsCount": 13,
          "notificationsCount": 58,
          "nextSequenceNumber": 21
        }
      ]
    }
  },
  {
    "connection": {
      "endpoint": {
        "url": "opc.tcp://localhost:21878",
        "securityMode": "none"
      },
      "group": "AssetStates",
      "options": "noComplexTypeSystem, noSubscriptionTransfer"
    }
  },
  {
    "connection": {
      "endpoint": {
        "url": "opc.tcp://localhost:21878",
        "securityMode": "none"
      },
      "options": "noComplexTypeSystem, noSubscriptionTransfer"
    }
  }
]

**Comment by Haeavar** [comment]
After some more investigation it seems, that the memory leak is related to the OPC UA server restart. Our setup is an OPC UA aggregation server with multiple underlying OPC UA server which are restarted multiple times per day.
In a local debug profiler session I simulated the same. After each OPC UA server restart the memory consumption increased with a lot of dead objects:

<img width="1882" height="770" alt="Image" src="https://github.com/user-attachments/assets/0c549445-b3aa-491b-9e25-9235bcfb95c9" />

For you information: This issue is **not in** version 2.9.11 but started with version 2.9.12. Maybe this helps to identify the root cause.

If you need more information, please let me now.

**Comment by marcschier** [comment]
Yes, looks like the issue was in subscription handling.  A subscription is not cleaned up in the case of reconnect.  I believe this is fixed in 2.9.15-preview5.  But I would need to check the memory allocations now with this scenario to validate.

**Comment by Haeavar** [comment]
@marcschier 
It seems, that the memory leak comes from the `InitializeMetrics()` within the `Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaClient`. If I comment the line `InitializeMetrics();` in the constructor  the memory consumption stays pretty much the same.

I'm wondering, why the `_meter` member is never disposed in the OpcUaClient? And why is the `ServiceCallContext.Dispose()` method does not dispose the `_client`?

**Comment by marcschier** [comment]
This shows a design flaw in the client manager which does not clean up clients but keeps them around disconnected for pretty much ever until the client manager is disposed.  And yes, the more clients are created (with different configurations) the more will accrue.  This should be fixed for sure.
